export enum processorRoutes {
  index = '/processor',
  rates = '/processor/rates',
  settings = '/processor/settings',
  mapsSettings = '/processor/settings/maps',
  mapDisplayingSettings = '/processor/settings/map-displaying',
  linesSettings = '/processor/settings/lines',
  mainSettings = '/processor/settings/main',
  transitions = '/processor/horoscopes/transitions',
  horoscopes = '/processor/horoscopes',
  dashi = '/processor/horoscopes/dashi',
  varshapkhala = '/processor/horoscopes/varshapkhala',
  ashtakavarga = '/processor/horoscopes/ashtakavarga',
  zones = '/processor/horoscopes/zones',
  yogas = '/processor/horoscopes/yogas',
  rectification = '/processor/horoscopes/rectification',
  myHoroscopes = '/processor/my-horoscopes',
}
